apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: car-management
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: car-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec: 
      containers: 
        - name: backend
          image: car-management-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: car-management
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort